#include "./supplier.h"

struct character characters[16]={{
    .letter = 'a',
    .graph =    {
    false, false, false, false, false, false, false, false,
    false, false, true, true, true, true, false, false,
    false, false, false, false, false, false, true, false,
    false, false, false, false, false, false, true, false,
    false, false, true, true, true, false, true, false,
    false, true, false, false, false, true, true, false,
    false, true, false, false, false, true, true, false,
    false, false, true, true, true, false, true, false,
    false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false,
},
    .graph_width = 8,
},{  
    .letter= 'A',
    .graph_width = 8,
    .graph =     {
    false, false, false, true, true, false, false, false,
    false, false, true, false, false, true, false, false,
    false, false, true, false, false, true, false, false,
    false, true, false, false, false, false, true, false,
    false, true, true, true, true, true, true, false,
    false, true, false, false, false, false, true, false,
    false, true, false, false, false, false, true, false,
    false, true, false, false, false, false, true, false,
    false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false,
},
},{
    .letter='b',
    .graph={
        false,false,false,false,false,false,
        false,true,false,false,false,false,
        false,true,false,false,false,false,
        false,true,false,false,false,false,
        false,true,true,true,false,false,
        false,true,false,false,true,false,
        false,true,false,false,true,false,
        false,true,true,true,false,false,
        false,false,false,false,false,false,
        false,false,false,false,false,false,
    },
    .graph_width=6,
},{
    .letter='B',
    .graph={
        false,true,true,true,false,false,false,
        false,true,false,false,true,false,false,
        false,true,false,false,true,false,false,
        false,true,true,true,false,false,false,
        false,true,false,false,true,false,false,
        false,true,false,false,false,true,false,
        false,true,false,false,false,true,false,
        false,true,true,true,true,false,false,
        false,false,false,false,false,false,false,
        false,false,false,false,false,false,false,
    },
    .graph_width=7
},{
    .letter='c',
    .graph={
        false,false,false,false,false,false,false,
        false,false,false,false,false,false,false,
        false,false,false,true,true,false,false,
        false,false,true,false,false,true,false,
        false,true,false,false,false,false,false,
        false,true,false,false,false,false,false,
        false,false,true,false,false,true,false,
        false,false,false,true,true,false,false,
        false,false,false,false,false,false,false,
        false,false,false,false,false,false,false,
    },
    .graph_width=7,
},{
    .letter='C',
    .graph={
        false,false,false,true,true,true,false,false,
        false,false,true,false,false,false,true,false,
        false,true,false,false,false,false,false,false,
        false,true,false,false,false,false,false,false,
        false,true,false,false,false,false,false,false,
        false,true,false,false,false,false,false,false,
        false,false,true,false,false,false,true,false,
        false,false,false,true,true,true,false,false,
        false,false,false,false,false,false,false,false,
        false,false,false,false,false,false,false,false,
    },
    .graph_width=8,
},{
    .letter='d',
    .graph={
        false,false,false,false,false,false,false,
        false,false,false,false,false,true,false,
        false,false,false,false,false,true,false,
        false,false,true,true,false,true,false,
        false,true,false,false,true,true,false,
        false,true,false,false,false,true,false,
        false,true,false,false,true,true,false,
        false,false,true,true,false,true,false,
        false,false,false,false,false,false,false,
        false,false,false,false,false,false,false,
    },
    .graph_width=7,
},{
    .letter='D',
    .graph={
        false,true,true,true,false,false,false,false,
        false,true,false,false,true,false,false,false,
        false,true,false,false,false,true,false,false,
        false,true,false,false,false,false,true,false,
        false,true,false,false,false,false,true,false,
        false,true,false,false,false,true,false,false,
        false,true,false,false,true,false,false,false,
        false,true,true,true,false,false,false,false,
        false,false,false,false,false,false,false,false,
        false,false,false,false,false,false,false,false,
    },
    .graph_width=8,
},{
    .letter='e',
    .graph={
        false,false,false,false,false,false,false,
        false,false,true,true,true,false,false,
        false,true,false,false,false,true,false,
        false,true,false,false,false,true,false,
        false,false,true,true,true,false,false,
        false,true,false,false,false,false,false,
        false,true,false,false,false,false,false,
        false,false,true,true,true,false,false,
        false,false,false,false,false,false,false,
        false,false,false,false,false,false,false,
    },
    .graph_width=7,
},{
    .letter='E',
    .graph={
        false,true,true,true,true,true,true,false,
        false,true,false,false,false,false,false,false,
        false,true,false,false,false,false,false,false,
        false,true,true,true,true,false,false,false,
        false,true,false,false,false,false,false,false,
        false,true,false,false,false,false,false,false,
        false,true,true,true,true,true,true,false,
        false,false,false,false,false,false,false,false,
        false,false,false,false,false,false,false,false,
    },
    .graph_width=8,
},{
    .letter='f',
    .graph={
        false,false,false,true,true,false,
        false,false,true,false,false,false,
        false,true,false,false,false,false,
        false,true,false,false,false,false,
        false,true,true,true,true,false,
        false,true,false,false,false,false,
        false,true,false,false,false,false,
        false,true,false,false,false,false,
        false,false,false,false,false,false,
        false,false,false,false,false,false,
    },
    .graph_width=6,
},{
    .letter='F',
    .graph={
        false,true,true,true,true,true,true,false,
        false,true,false,false,false,false,false,false,
        false,true,false,false,false,false,false,false,
        false,true,true,true,true,true,false,false,
        false,true,false,false,false,false,false,false,
        false,true,false,false,false,false,false,false,
        false,true,false,false,false,false,false,false,
        false,true,false,false,false,false,false,false,
        false,false,false,false,false,false,false,false,
        false,false,false,false,false,false,false,false,
    },
    .graph_width=8,
},{
    .letter='g',
    .graph={
        false,false,false,false,false,false,
        false,false,false,false,false,false,
        false,false,false,false,false,false,
        false,false,true,true,false,false,
        false,true,false,false,true,false,
        false,true,false,false,true,false,
        false,false,true,true,false,false,
        false,false,false,false,true,false,
        false,true,false,false,true,false,
        false,false,true,true,false,false,
    },
    .graph_width=6,
},{
    .letter='G',
    .graph={
        false,false,false,true,true,true,false,false,
        false,false,true,false,false,false,true,false,
        false,true,false,false,false,false,false,false,
        false,true,false,false,false,false,false,false,
        false,true,false,true,true,true,false,false,
        false,true,false,false,false,false,true,false,
        false,true,false,false,false,false,true,false,
        false,false,true,true,true,true,false,false,
        false,false,false,false,false,false,false,false,
        false,false,false,false,false,false,false,false,
    },
    .graph_width=8,
},{
    .letter='h',
    .graph={
        false,true,false,false,false,false,false,
        false,true,false,false,false,false,false,
        false,true,false,false,false,false,false,
        false,true,false,true,true,false,false,
        false,true,true,false,false,true,false,
        false,true,false,false,false,true,false,
        false,true,false,false,false,true,false,
        false,true,false,false,false,true,false,
        false,false,false,false,false,false,false,
        false,false,false,false,false,false,false,
    },
    .graph_width=7,
},{
    .letter='i',
    .graph={
        false,false,false,
        false,false,false,
        false,true,false,
        false,false,false,
        false,true,false,
        false,true,false,
        false,true,false,
        false,true,false,
        false,false,false,
        false,false,false,
    },
    .graph_width=3,
},{
    .letter='I',
    .graph={
        false,true,true,true,false,
        false,false,true,false,false,
        false,false,true,false,false,
        false,false,true,false,false,
        false,false,true,false,false,
        false,false,true,false,false,
        false,false,true,false,false,
        false,true,true,true,false,
        false,false,false,false,false,
        false,false,false,false,false,
    },
    .graph_width=5,
},{
    .letter='j',
    .graph={
        false,false,false,false,false,false,
        false,false,false,false,true,false,
        false,false,false,false,false,false,
        false,false,false,false,true,false,
        false,false,false,false,true,false,
        false,false,false,false,true,false,
        false,true,false,false,true,false,
        false,true,false,false,true,false,
        false,true,false,false,true,false,
        false,false,true,true,false,false
    },
    .graph_width=6,
},{
    .letter='J',
    .graph={
        false,true,true,true,true,true,true,false,
        false,false,false,false,true,false,false,false,
        false,false,false,false,true,false,false,false,
        false,false,false,false,true,false,false,false,
        false,false,false,false,true,false,false,false,
        false,true,false,false,true,false,false,false,
        false,true,false,false,true,false,false,false,
        false,false,true,true,false,false,false,false,
        false,false,false,false,false,false,false,false,
        false,false,false,false,false,false,false,false,
    }
},{
    .letter='k',
    .graph={
        false,false,false,false,false,false,false,
        false,false,false,false,false,false,false,
        false,true,false,false,true,false,false,
        false,true,false,true,false,false,false,
        false,true,true,false,false,false,false,
        false,true,false,true,false,false,false,
        false,true,false,false,true,false,false,
        false,true,false,false,false,true,false,
        false,false,false,false,false,false,false,
        false,false,false,false,false,false,false,
    },
    .graph_width=7,
},{
    .letter='K',
    .graph={
        false,true,false,false,false,true,false,false,
        false,true,false,false,true,false,false,false,
        false,true,false,true,false,false,false,false,
        false,true,true,false,false,false,false,false,
        false,true,false,true,false,false,false,false,
        false,true,false,false,true,false,false,false,
        false,true,false,false,false,true,false,false,
        false,true,false,false,false,false,true,false,
        false,false,false,false,false,false,false,false,
        false,false,false,false,false,false,false,false,
    },
    .graph_width=8,
}};

character* get_character(char input){
    //character* characters = (character*) 0x5000;
    for(int i=0; i<26; i++){
        if(characters[i].letter == input){
            return &characters[i];
        }
    }
    return NULL;
}